/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_840750_11_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_840750_2[] = { "value" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_840750_10_axes[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
const uint32_t ei_dsp_config_840750_10_axes_size = 16;
ei_dsp_config_raw_t ei_dsp_config_840750_10 = {
    10, // uint32_t blockId
    1, // int implementationVersion
    16, // int length of axes
    1.0f // float scale-axes
};

const float ei_dn_standard_scaler_mean_840750_10[16] = { 5.177466776448653, 15.032045240339302, 27317.259754541643, 2138.557971599202, 8204.539768101944, 227.98925286900348, 227.98925286900348, 735.9692520235881, 288, 646.4434865139981, 2.3562590842072733, 0.9980000257492065, 12.313418472059135, 1.0295061312466844, 33.76853827626513, 0.6638789400255471 };
const float ei_dn_standard_scaler_scale_840750_10[16] = { 0.3810886886862574, 0.12921020143172068, 0.00004513652885986692, 0.0012907644459360182, 0.0009168492777302268, 0.004986797935363221, 0.004986797935363221, 0.005755007001078614, 1, 0.013755023575723353, 0.9214701262990096, 1, 0.18728273947991017, 96.21187549101849, 0.03874888527619977, 1.970893005843334 };
const float ei_dn_standard_scaler_var_840750_10[16] = { 6.88569660652077, 59.897182339141104, 490844224.3903754, 600213.8484301236, 1189608.628624725, 40212.07260293241, 40212.07260293241, 30193.140462978205, 0, 5285.393445689112, 1.1777076056649678, 0, 28.51047764465874, 0.00010802956786190692, 666.0112626776124, 0.2574387413125547 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_840750_10 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_840750_10,
    .mean_data_len = 16,
    .scale_data = (float *)ei_dn_standard_scaler_scale_840750_10,
    .scale_data_len = 16,
    .var_data = (float *)ei_dn_standard_scaler_var_840750_10,
    .var_data_len = 16
};
ei_data_normalization_t ei_data_normalization_config_840750_10 = {
    (void *) &ei_data_normalization_standard_scaler_config_840750_10, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_840750_2_size = 1;
ei_model_dsp_t ei_dsp_blocks_840750_2[ei_dsp_blocks_840750_2_size] = {
    { // DSP block 10
        10,
        16, // output size
        &extract_raw_features, // DSP function pointer
        (void*)&ei_dsp_config_840750_10, // pointer to config struct
        ei_dsp_config_840750_10_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_840750_10_axes_size, // number of axes
        1, // version
        nullptr, // factory function
        &ei_data_normalization_config_840750_10, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_840750_11 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_840750_11_init,
    .model_invoke = &tflite_learn_840750_11_invoke,
    .model_reset = &tflite_learn_840750_11_reset,
    .model_input = &tflite_learn_840750_11_input,
    .model_output = &tflite_learn_840750_11_output,
};

const uint8_t ei_output_tensors_indices_840750_11[1] = { 0 };
const uint8_t ei_output_tensors_size_840750_11 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_840750_11 = {
    .implementation_version = 1,
    .block_id = 11,
    .output_tensors_indices = ei_output_tensors_indices_840750_11,
    .output_tensors_size = ei_output_tensors_size_840750_11,
    .quantized = 0,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_840750_11,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_840750_2_size = 1;
const uint32_t ei_learning_block_840750_11_inputs[1] = { 10 };
const uint8_t ei_learning_block_840750_11_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_840750_2[ei_learning_blocks_840750_2_size] = {
    {
        11,
        &run_nn_inference,
        (void*)&ei_learning_block_config_840750_11,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_840750_11_inputs,
        ei_learning_block_840750_11_inputs_size,
    },
};

const size_t ei_postprocessing_blocks_840750_2_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_840750_2[ei_postprocessing_blocks_840750_2_size] = {
    {
        .block_id = 11,
        .type = EI_CLASSIFIER_MODE_REGRESSION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_f32,
        .display_fn = NULL,
        .config = NULL,
        .input_block_id = 11
    },
};

const uint8_t freeform_outputs_840750_2_size = 0;

uint32_t *freeform_outputs_840750_2 = nullptr;

const ei_impulse_t impulse_840750_2 = {
    .project_id = 840750,
    .project_owner = "RoseMaker",
    .project_name = "RoseMaker-project-Compressor",
    .impulse_id = 2,
    .impulse_name = "Impulse Compressor",
    .deploy_version = 3,

    .nn_input_frame_size = 16,
    .raw_sample_count = 1,
    .raw_samples_per_frame = 16,
    .dsp_input_frame_size = 1 * 16,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 1,
    .frequency = 0,

    .dsp_blocks_size = ei_dsp_blocks_840750_2_size,
    .dsp_blocks = ei_dsp_blocks_840750_2,

    .learning_blocks_size = ei_learning_blocks_840750_2_size,
    .learning_blocks = ei_learning_blocks_840750_2,

    .postprocessing_blocks_size = ei_postprocessing_blocks_840750_2_size,
    .postprocessing_blocks = ei_postprocessing_blocks_840750_2,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "Lever_pos + Ship_speed + GTT_torque + GT_rpm + GG_rpm + Starboard_Prop_T + Port_Prop_T + HP_T_exit_temp + GT_Comp_in_temp + GT_Comp_out_temp + HP_T_exit_press + GT_Comp_in_press + GT_Comp_out_press + GT_exhaust_press + TIC_control + Fuel_flow",
    .slice_size = (1/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 1,
    .categories = ei_classifier_inferencing_categories_840750_2,
    .results_type = EI_CLASSIFIER_TYPE_REGRESSION,
    .freeform_outputs_size = freeform_outputs_840750_2_size,
    .freeform_outputs = freeform_outputs_840750_2
};

ei_impulse_handle_t impulse_handle_840750_2 = ei_impulse_handle_t( &impulse_840750_2 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_840750_2;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_840750_2;
const auto ei_dsp_blocks_size = ei_dsp_blocks_840750_2_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_840750_2;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
